### ISSUE TITLE
Test fails on Windows when getpwuid is not available

### ISSUE THREAD

**Issue by nanis** [perlancar/perl-Complete-Bash#1]
The relevant code is

```
subtest "tilde expansion" => sub {
    my @ent = getpwuid($>);
```

in `t/parse_cmdline.t`. Naively, I do not see any problem with 

```
my @ent = eval { getpwuid($>) };
```

as the next line skips the rest of the tests if `@ent` is empty. That way, `cpan-outdated | cpanm` can run without intervention on my machine ;-)

That aside, your test seems to use this call just to get a home directory. Therefore, wouldn't it make sense to use `File::HomeDir` ... That does not interfere with the `Bash` part of the module does it?

HTH,

-- Sinan

<pre>t\parse_cmdline.t ......... 1/?
#   Failed test 'tilde expansion'
#   at t\parse_cmdline.t line 150.
# Exception in subtest 'tilde expansion': The getpwuid function is unimplemented at t\parse_cmdline.t line 126.
The getpwuid function is unimplemented at t\parse_cmdline.t line 126.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 9.
t\parse_cmdline.t ......... Dubious, test returned 2 (wstat 512, 0x200)</pre>

**Comment by perlancar** [comment]
Sorry for the very late response, missed this PR/issue (didn't receive notification from GitHub).

I've fixed this issue (commit 76b8014) after seeing CPANTesters reports.
