### ISSUE TITLE
Bug in join_wordbreak_words

### ISSUE THREAD

**Issue by regina-verbae** [perlancar/perl-Complete-Bash#2]
As an example, with the following COMP_LINE (with ^ mark for cursor position):

`cmd --^foo=bar`

Then `parse_cmdline` returns:

Without `truncate_current_word`:
`[ [ 'cmd',  '--foo', '=', 'bar' ], 1 ]`
With `truncate_current_word`:
`[ [ 'cmd',  '--', '=', 'bar' ], 1 ]`

But this becomes the following under `join_wordbreak_words`:

Without `truncate_current_word`:
`[ [ 'cmd', '--foo=bar' ], 1 ]`
With `truncate_current_word`:
`[ [ 'cmd', '--=bar' ], 1 ]`

Both of these do not tab-complete in the expected way.

Pull request forthcoming.  I believe the preferred behavior would be to never modify CWORD in `join_wordbreak_words`.

**Comment by perlancar** [comment]
Merged. Closing this issue. Thanks!
